### PR TITLE
Support for Gazebo 8 and 9

### PR DESCRIPTION
**Pull request by dekent**
I updated the simulation code to run on newer versions of Gazebo (we're testing with actors, and require functionality not included in the default Gazebo version included with ROS kinetic).  The code still compiles and runs correctly with Gazebo 7 (kinetic's default), and has also been tested on ROS kinetic with Gazebo 8 and Gazebo 9 (installing ros-kinetic-gazebo8-ros-pkgs or ros-kinetic-gazebo9-ros-pkgs allows this fairly painlessly).

I figured I'd make a pull request in case this is useful to anyone outside of our lab.

### CODE REVIEW

**Comment by Pedro-Roque** [comment]
Cool! I'm working on a Ubuntu 18 compatible version, will share here once done.

**Comment by bcoltin** [comment]
Hi David, we would like to merge this, could you please submit this copyright agreement if you haven't already? (just sign and send to the email at the bottom) Thank you! https://www.nasa.gov/sites/default/files/atoms/files/astrobee_individual_contributor_license_agreement.pdf

**Comment by dekent** [comment]
I think I submitted one earlier, but just in case I signed and emailed a copy of the agreement.  Let me know if you need anything else!

**Comment by marinagmoreira** [comment]
Hi David!
This pull request was merged in release v0.11.0.
Thank you so much for your contribution!

**Pull request closed without merging**
