### PR TITLE
Prevent CPU Mem Monitor Blocking on Startup

### PR DESCRIPTION
**Pull request by bcoltin**
Starts a separate thread to get all PIDs so the heartbeat can be published immediately.

### CODE REVIEW

**Review by kbrowne15 — APPROVED** [review]

**Review by marinagmoreira — APPROVED** [review]
looks good! was this tested on the robot?

**Comment by bcoltin** [comment]
No, only on the simulator. Should we wait to merge until testing on the robot? Probably makes more sense to wait until next testing session rather than going to lab just for this.

**Comment by marinagmoreira** [comment]
> No, only on the simulator. Should we wait to merge until testing on the robot? Probably makes more sense to wait until next testing session rather than going to lab just for this.

no worries, I'll test it quickly and merge this in :)

**Comment by bcoltin** [comment]
Thanks!

**Comment by marinagmoreira** [comment]
tested in the lab

**Comment by bcoltin** [comment]
Thanks!

**Pull request merged**
