### PR TITLE
Update monitor plugins and fix heartbeat name bug.

### PR DESCRIPTION
**Pull request by bcoltin**
Please make sure I'm not breaking anything else with the changes to ff_component.

### CODE REVIEW

**Comment by marinagmoreira** [comment]
> Please make sure I'm not breaking anything else with the changes to ff_component.

That function is only used for gazebo plugins, so you're good!

**Review by marinagmoreira — APPROVED** [review]
It's awesome that we reduced the amount of plugins!

**Comment by marinagmoreira** [comment]
I also tested this in humble and all the heartbeats were being printed well with `ros2 topic echo /heartbeat`

**Review by kbrowne15 — APPROVED** [review]
Great idea on the heartbeat plugin!

**Pull request merged**
