### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by marinagmoreira**

### CODE REVIEW

**Comment by marinagmoreira** [comment]
Converting this back to draft to add fixes from https://github.com/nasa/astrobee/issues/556

**Review by bcoltin — APPROVED** [review]
Looks great! Thank you!

**Review by trey0 — APPROVED** [review]
Thanks for working on this!

**Comment by LadySkyWatcher** [comment]
🎉 Thanks so much for updating the Docker docs! The new ROS1 build instructions are crystal‑clear and worked flawlessly in my local setup.
I’d love to see something similar for ROS2 down the line—happy to help test when that’s ready!

**Pull request merged**
