### PR TITLE
ROS2: Dock+Nav Cam plugin

### PR DESCRIPTION
**Pull request by Pedro-Roque**
First take at the navcam plugin.

### CODE REVIEW

**Comment by marinagmoreira** [comment]
can you pull from the nasa/ros2 branch? We have those CI actions updated

**Comment by Pedro-Roque** [comment]
Same here. I probably should have done a rebase so that you don't see previous commits there though

**Comment by Pedro-Roque** [comment]
Fixed the history and everything compiles - also added the dock cam plugin to this

**Comment by bcoltin** [comment]
So, the callbacks for changes in subscribers are dropped in ros2. This means the ToggleCallback in the current version is only called intiailly, and if there are no subscribers, I believe the images will never be published, even if subscribers are added later.

I guess we need to change this to always publish? Or stick a timer to call ToggleCallback repeatedly?

What do you all think?

**Review by marinagmoreira — APPROVED** [review]

**Review by marinagmoreira — APPROVED** [review]

**Review by bcoltin — APPROVED** [review]
Thanks!

**Comment by Pedro-Roque** [comment]
Should this be merged? I'll work on top of it for the next camera ports

**Pull request merged**
