### PR TITLE
Fix depth odom nodelet manager

### PR DESCRIPTION
**Pull request by rsoussan**
Addresses issue 561: https://github.com/nasa/astrobee/issues/561

### CODE REVIEW

**Comment by marinagmoreira** [comment]
This should be tested on the robot before merging because there are some configurations where it causes the fsw to crash at startup just by changing managers

**Review by trey0 — APPROVED** [review]
Looks good to me.

Marina has a good point about testing on the robot.

**Review by bcoltin — APPROVED** [review]
Yay, thanks!

**Review by tejusp — APPROVED** [review]

**Comment by marinagmoreira** [comment]
Tested in the lab, started and stopped fsw 3 times, flew the robot around, all good

**Pull request merged**
