### PR TITLE
Added Groundtruth Creation Scripts

### PR DESCRIPTION
**Pull request by rsoussan**
Added scripts to create groundtruth for a bagfile and generate a new groundtruth map and results bagfile.  Also added a helper script to run multiple groundtruth creation processes in parallel.

### CODE REVIEW

**Review by bcoltin — CHANGES_REQUESTED** [review]
Could you add a comment to the top of each of the scripts explaining what it does and how to use it?

**Comment by trey0** [comment]
> Could you add a comment to the top of each of the scripts explaining what it does and how to use it?

A good pattern is to format the comment as a Python docstring (just a bare string literal at the top of the file, conventionally written with triple quotes) and there is a handy pattern for including the docstring in the argparse help [1].

[1] https://stackoverflow.com/questions/18106327/display-pydocs-description-as-part-of-argparse-help

**Comment by rsoussan** [comment]
> Could you add a comment to the top of each of the scripts explaining what it does and how to use it?

Done using Trey's suggestion

**Comment by rsoussan** [comment]
> Could you add a comment to the top of each of the scripts explaining what it does and how to use it?

Done using Trey's suggestion

**Comment by bcoltin** [comment]
Could you say a bit more? Like, what is a groundtruth map? I still am confused about what this does.

**Comment by rsoussan** [comment]
> Could you say a bit more? Like, what is a groundtruth map? I still am confused about what this does.

Ok good point.  I updated the scripts again, let me know if they need further clarification.

**Review by bcoltin — APPROVED** [review]

**Comment by marinagmoreira** [comment]
The documentation in tools/graph_bag/readme.md doesn't mention this.

Unrelated to this, also noticed that there is a repeated merge_bag tool on this node (besides the one in localization/localization_node/tools/merge_bags.cc)

**Comment by rsoussan** [comment]
> The documentation in tools/graph_bag/readme.md doesn't mention this.
> 
> Unrelated to this, also noticed that there is a repeated merge_bag tool on this node (besides the one in localization/localization_node/tools/merge_bags.cc). Oleg converted the old merge_bag tool in the localization_node to c++ because the python api didn't work when we had sci cam images.

Ok I'll update the readme.  The merge_bags tool in graph_bag automatically finds bags in a directory with a given prefix and also optionally filters to only include localization topics.  This is useful to easily combine hivemind bags for localization testing

**Review by marinagmoreira — APPROVED** [review]

**Pull request merged**
