### PR TITLE
Fix platform name + better default_robot naming

### PR DESCRIPTION
**Pull request by marinagmoreira**
platform name checked after init; adding / line to make it work
changing default to default_robot for better understandability

ps. not everyone needs to review this, just whoever has time

### CODE REVIEW

**Comment by rsoussan** [comment]
Looks good - I think you need to do the same change for graph_localizer_nodelet.cc as done for imu_augmentor_nodelet.cc

**Comment by oleg-alexandrov** [comment]
Marina, thank you for renaming 'default' to 'default_robot'. I think this should be done also in isaac, for consistency, as the same logic is used there. Hope it won't be too much extra work.

**Review by bcoltin — CHANGES_REQUESTED** [review]
Let's merge in develop to pass the linter and respond to Ryan's suggestion and then we should be good.

**Comment by marinagmoreira** [comment]
> Looks good - I think you need to do the same change for graph_localizer_nodelet.cc as done for imu_augmentor_nodelet.cc

Good point, does the imu_aug need:
ff_common::InitFreeFlyerApplication(getMyArgv());
there too?

**Review by bcoltin — APPROVED** [review]

**Pull request merged**
