### PR TITLE
Multibridge cleanup

### PR DESCRIPTION
**Pull request by rgarciaruiz**
* Remove unnecessary library from CMake file
* Remove unnecessary code from astrobee_astrobee_bridge.cc

### CODE REVIEW

**Comment by marinagmoreira** [comment]
@rgarciaruiz, this PR is flagged as Draft, is that accurate or is it ready for review?

**Comment by rgarciaruiz** [comment]
I was planning to test this using both ground units first, however, since it actually works in simulation, the changes are very minor, and it does not affect immediate upcoming activities I say we can probably do that in the next software release. 
I'll go ahead and mark it as ready.

**Review by kbrowne15 — APPROVED** [review]

**Comment by marinagmoreira** [comment]
> I was planning to test this using both ground units first, however, since it actually works in simulation, the changes are very minor, and it does not affect immediate upcoming activities I say we can probably do that in the next software release. I'll go ahead and mark it as ready.

Do we have a test scenario for astrobee_astrobee_bridge? Not sure if it's in the current release testing, but we can add to it :)

**Comment by rgarciaruiz** [comment]
yeah, main issue is that you need to have two robots running FSW (and wannabee has Ubuntu 20, so we need to cross-compile for two Ubuntu versions). But, yes, we can start working on adding this test to the procedure, maybe as optional for now.

**Comment by marinagmoreira** [comment]
@rgarciaruiz next time, make sure to squash merge!!!

**Comment by rgarciaruiz** [comment]
> @rgarciaruiz next time, make sure to squash merge!!!

Yes, always, that's the option I chose, did something different happen?

**Comment by marinagmoreira** [comment]
> > @rgarciaruiz next time, make sure to squash merge!!!
> 
> Yes, always, that's the option I chose, did something different happen?

Sorry I was too quick to reply :( the pr says "merged commit" so I thought it wasn't squash commit, but apparently it always says that regardless. I checked the commit history and everything looks great! (and proceeded to remove my comment)

**Pull request merged**
