### PR TITLE
Added enable re-plan to mobility settings telemetry.

### PR DESCRIPTION
**Pull request by kbrowne15**
Added what enable re-plan is set to in the executive to the mobility settings telemetry message. I should have done this when I added the enable re-plan command but forgot.

### CODE REVIEW

**Review by bcoltin — APPROVED** [review]

**Comment by bcoltin** [comment]
@kbrowne15 feel free to merge once the build passes

**Comment by trey0** [comment]
Do any subscribers need to be modified, or at least recompiled, to maintain compatibility after this change? (Like does the Facility team need to update ground tools?)

**Comment by kbrowne15** [comment]
Yes, the IDLs need to be recompiled for GDS and it is on my list of things to do. However the mobility settings message was never "manually" added to GDS so it won't break anything in GDS and only shows up in the debug tab in the raw telemetry window. Since the facility doesn't use this window, it is not high priority.

**Comment by trey0** [comment]
Thanks, that makes sense. Is it worth double-checking that publishing messages with the new IDL doesn't surprise-crash a GDS control station compiled with the old IDL, even though we think GDS "shouldn't be using it" outside of rare corner cases?

**Comment by kbrowne15** [comment]
I already tested it before the pr and it doesn't crash gds.

**Pull request merged**
