### PR TITLE
Changed imu aug publish rate to 62.5

### PR DESCRIPTION
**Pull request by rsoussan**
Simple change to publish IMU aug messages at 62.5Hz instead of 100Hz.

### CODE REVIEW

**Review by bcoltin — APPROVED** [review]
That is indeed pretty simple :)

**Comment by marinagmoreira** [comment]
I'll test this first thing tomorrow to make sure the 62.5Hz is constant during a granite square run

**Comment by bcoltin** [comment]
@rsoussan what is the status on this?

**Comment by rsoussan** [comment]
> 

It was tested but I think it didn't improve controller functionality (or maybe we found another reason for the controller having issues).  @marinagmoreira might have some more insight.

**Comment by marinagmoreira** [comment]
yeah it made it worse :/

**Comment by bcoltin** [comment]
Ok, we should go back to this and try to figure out what was happening.

**Review by tejusp — APPROVED** [review]

**Comment by bcoltin** [comment]
@rsoussan did we ever figure out what is going on here? should we close this?

**Review by tejusp — CHANGES_REQUESTED** [review]
Needs validation

**Comment by rsoussan** [comment]
> @rsoussan did we ever figure out what is going on here? should we close this?

No, we can probably close it.

**Pull request closed without merging**
