### PR TITLE
Drag model fixed for Astrobee sim

### PR DESCRIPTION
**Pull request by albee**
See #423 

Issue was the `drag_.Normalize()` command also updates the math::Vector3 object itself, so after normalization the magnitude of `drag_.GetLength()` was getting reset to 1. @Pedro-Roque confirmed this was also happening for non-Kinetic builds. Drag forces applied to the model are fixed with this commit.

### CODE REVIEW

**Comment by bcoltin** [comment]
@albee Loooks like you might need to import a header for math::Vector3? While you're at it, could you put just the part that is different (getting the vector) inside the #if else and the rest outside it?

**Comment by marinagmoreira** [comment]
> @albee Loooks like you might need to import a header for math::Vector3? While you're at it, could you put just the part that is different (getting the vector) inside the #if else and the rest outside it?

It seems that newer versions of gazebo use ignition::math::Vector3d

**Comment by albee** [comment]
@Pedro-Roque could you check the build for your 20.04 version of the Astrobee sim? Seems like there's a different dependency for Vector3 with newer Gazebo.

**Comment by Pedro-Roque** [comment]
I'll fix it, one sec

**Comment by Pedro-Roque** [comment]
Done - can we re-run the tests?

**Comment by marinagmoreira** [comment]
> Done - can we re-run the tests?

@Pedro-Roque I think it might be a problem on the github side, we got the same problem last week and it fixed itself (but at the time it was flagged in https://www.githubstatus.com/)

**Review by marinagmoreira — APPROVED** [review]

**Comment by marinagmoreira** [comment]
I just opened another PR and the actions triggered, so maybe we need to either redo this PR (close and open it again) or do a commit to force the actions to start

**Comment by albee** [comment]
Reopened to retrigger actions (hopefully).

**Pull request merged**
